### ISSUE TITLE
Add firebase authentication service and sign up component

### ISSUE THREAD

**Issue by SahithiAmmana** [SahithiAmmana/trackaday#1]
Project is added in firebase at https://console.firebase.google.com/u/0/project/track-a-day/authentication/users. Add firebase library and service implementation to the app code.

**Comment by SahithiAmmana** [comment]
Created PR #2 to do the task

**Comment by mithila-reddy** [comment]
Created PR #3 to add a sign-in component and link to the sign in, sign-up page from the dashboard.

**Comment by SahithiAmmana** [comment]
Merged #2 and #3
