### ISSUE TITLE
Fetch data from FireBase

### ISSUE THREAD

**Issue by SaiPavanYalla** [SahithiAmmana/trackaday#5]

**Comment by mithila-reddy** [comment]
For Todo Component, fetch data functionality is added.
Refer this commit: https://github.com/SahithiAmmana/trackaday/commit/c7097c83bec30921214413dc683ad7d161b72055

**Comment by vineethdasi** [comment]
For the analysis Component, fetch data functionality is added.
refer this commit https://github.com/SahithiAmmana/trackaday/commit/bb4e66fafe760e6bc9fcd9646b739705703879ae

**Comment by SahithiAmmana** [comment]
Verified 👍
